from django.contrib import admin
from django.urls import path
import backend.views as views
urlpatterns = [
    #api
    path('api/rooms/<int:guestCount>/<str:roomType>',views.roomFilter,name="roomsFilter"),
    path("api/authGuest",views.authGuest,name="authGuest"),
    path("api/authStaff",views.authStaff,name="authStaff"),
    path("api/StaffByRole/<str:role>",views.StaffByRole,name="StaffByRole"),
    path('api/roomsData',views.roomsData,name="roomsData"),
    path('api/authStays',views.authStay,name="authStay"),
    path('api/stay/<int:stayID>/services',views.stayServiceData,name="stayServiceData"),
    path('api/stay/<int:stayID>/orders',views.stayOrderData,name="stayOrderData"),
    path('api/totalAmount/<int:stayID>',views.totalAmount,name='totalAmount'),
    path('api/roomTypeProfit/', views.roomTypeProfit,name="roomTypeProfit"),
    path('api/paymentMethodRevenue/',views.paymentMethodRevenue,name="paymentMethodRevenue"),
    #file routing
    path('cssFile/',views.css_file,name="css_file"),
    path('js_File/', views.js_file, name='js_file'),

    path('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path('loginPage/',views.loginPage,name="loginPage"),
    path('signupPage/',views.signupPage,name="signupPage"),
    path('bookings/',views.bookingList,name="bookingList"),
    path('servicesList/',views.servicesList,name="servicesList"),
    path('guests/',views.guestList,name="guests"),
    path('staffs/',views.staffList,name="staffs"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('staffProfile/',views.staffProfile,name="staffProfile"),
    path('rooms/',views.rooms,name="rooms"),
    path('services/',views.services,name="services"),
    path('menuList/', views.menu_list, name='menuList'),
    path('menuList/<str:type>',views.categoryMenu,name="categoryMenu"),
    path('contactUs/',views.contact_us,name="contactUs"),
    path('booking/',views.booking,name="booking"),
    path('roomDetail/<str:roomType>',views.roomDetail,name="roomDetail"),
    path('guestProfile/',views.guestProfile,name="guestProfile"),
    path('roomsList/',views.roomList,name="roomsList"),
    path('foodOrders/',views.foodOrders,name="foodOrders"),
    path('foodOrders/<str:state>/',views.foodOrdersWithState,name="foodOrderswithState"),
    path('serviceOrders/',views.serviceOrders,name="serviceOrders"),
    path('stayList/',views.stayList,name="stayList"),
    path('createStayPage/',views.createStayPage,name="createStayPage"),
    path('serviceRequestPage/',views.serviceRequestPage,name="serviceRequestPage"),
# functions
    path('logout/',views.logout,name="logout"),
    path('login/',views.login,name="login"),
    path('signup/',views.signup,name="signup"),
    path('createRoom/',views.createRoom,name="createRoom"),
    path('filterRooms/',views.filterRoom,name="filterRoom"),
    path('createOrder/',views.createOrder,name="createOrder"),
    path('createBooking/',views.createBooking,name="createBooking"),
    path('acceptBooking/',views.acceptBooking,name="acceptBooking"),
    path('deleteBooking/<int:bookingID>',views.deleteBooking,name='deleteBooking'),
    path('createStay/<int:bookingID>',views.createStay,name='createStay'),
    path('changeState/<str:state>/<int:orderID>',views.changeState,name="changeState"),
    path('createStays/',views.createStays,name="createStays"),
    path('createRequest/',views.createRequest,name="createRequest"),
    path('createStaff/',views.createStaff,name="createStaff"),
    path('assignStaff/',views.assignStaff,name="assignStaff"),
    path('endStay/',views.endStay,name="endStay"),
    path('deleteGuest/<int:guestID>',views.deleteGuest,name="deleteGuest"),
    path('updateRoom/',views.updateRoom,name="updateRoom"),
    path('deleteRoom/<int:roomID>/',views.deleteRoom,name="deleteRoom"),
    path('updateStaff/',views.updateStaff,name="updateStaff"),
    path('deleteStaff/<int:staffID>/',views.deleteStaff,name="deleteStaff"),
    ]
