# Generated by Django 5.2.3 on 2025-10-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('guestID', models.AutoField(primary_key=True, serialize=False)),
                ('guestName', models.CharField(max_length=255)),
                ('guestEmail', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('guestNRC', models.CharField(max_length=100)),
                ('guestPh', models.CharField(max_length=11, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('menuID', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('menuType', models.CharField(max_length=255, null=True)),
                ('cookingTime', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('roomCode', models.CharField(max_length=5)),
                ('building', models.CharField(choices=[('A', 'buildingA'), ('B', 'buildingB'), ('C', 'buildingC'), ('D', 'buildingD'), ('E', 'buildingE'), ('F', 'buildingF')], default='A', max_length=2)),
                ('accomodation', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('P', 'premium'), ('S', 'Standard'), ('D', 'Deluxe'), ('Su', 'Suite')], max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('staffName', models.CharField(max_length=255)),
                ('staffEmail', models.EmailField(max_length=255)),
                ('staffPassword', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('Kitchen Staff', 'kitchen staff'), ('HouseKeeping', 'housekeeping'), ('receptionist', 'Receptionist')], default='staff', max_length=255)),
                ('payRoll', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('checkIn', models.CharField(max_length=233, null=True)),
                ('checkOut', models.CharField(max_length=233, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guestID', models.ForeignKey(db_column='guestID', on_delete=django.db.models.deletion.CASCADE, to='backend.guests')),
                ('roomID', models.ForeignKey(db_column='roomID', on_delete=django.db.models.deletion.CASCADE, to='backend.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('stayID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Staying', max_length=255)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('guestID', models.ForeignKey(db_column='guestID', on_delete=django.db.models.deletion.CASCADE, to='backend.guests')),
                ('roomID', models.ForeignKey(db_column='roomID', on_delete=django.db.models.deletion.CASCADE, to='backend.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Transportation', 'T'), ('Laundary', 'L'), ('Maintainance', 'M'), ('Special Requests', 'Special'), ('HouseKeeping', 'H')], max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'P'), ('Accepted', 'A'), ('Reject', 'R')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(db_column='staffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.staffs')),
                ('stayID', models.ForeignKey(db_column='stayID', on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('menuItems', models.JSONField(default=list)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
        migrations.CreateModel(
            name='Transctions',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('Cash', 'C'), ('Credit Card', 'Credit'), ('Online Payment', 'Online')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(db_column='staffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.staffs')),
                ('stayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
    ]
