# Generated by Django 5.2.3 on 2025-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('staffName', models.CharField(max_length=255)),
                ('staffEmail', models.EmailField(max_length=255)),
                ('staffPassword', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('Kitchen Staff', 'kitchen staff'), ('HouseKeeping', 'housekeeping'), ('receptionist', 'Receptionist')], default='staff', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
