# Generated by Django 5.2.3 on 2025-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='payRoll',
            field=models.IntegerField(default=0),
        ),
    ]
