# Generated by Django 5.2.3 on 2025-10-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='roomType',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='roomID',
            field=models.ForeignKey(db_column='roomID', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
    ]
