# Generated by Django 5.2.3 on 2025-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(default='0'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(default='0'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_in',
            field=models.DateField(default='0'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_out',
            field=models.DateField(default='0'),
        ),
    ]
