# Generated by Django 5.2.3 on 2025-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bookings_roomtype_alter_bookings_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stays',
            name='guestCount',
            field=models.IntegerField(default=1),
        ),
    ]
