# Generated by Django 5.2.3 on 2025-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bookings_check_in_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(default='00-00-00'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(default='00-00-00'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_in',
            field=models.DateField(default='00-00-00'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_out',
            field=models.DateField(default='00-00-00'),
        ),
    ]
