# Generated by Django 5.2.3 on 2025-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_staffs_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('roomCode', models.CharField(max_length=5)),
                ('building', models.CharField(choices=[('A', 'buildingA'), ('B', 'buildingB'), ('C', 'buildingC'), ('D', 'buildingD'), ('E', 'buildingE'), ('F', 'buildingF')], default='A', max_length=2)),
                ('accomodation', models.IntegerField(default='1')),
                ('type', models.CharField(choices=[('P', 'premium'), ('E', 'economy'), ('A', 'average'), ('V', 'VIP')], max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], max_length=100)),
            ],
        ),
    ]
