# Generated by Django 5.2.3 on 2025-10-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('guestID', models.AutoField(primary_key=True, serialize=False)),
                ('guestName', models.CharField(max_length=255)),
                ('guestEmail', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('guestNRC', models.CharField(max_length=100)),
                ('guestPh', models.CharField(max_length=11, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('stayID', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('guestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.guests')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rooms')),
            ],
        ),
    ]
