# Generated by Django 5.2.3 on 2025-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_stays_guestcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guestCount',
            field=models.IntegerField(default=1),
        ),
    ]
