# Generated by Django 5.2.3 on 2025-10-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_bookings_check_in_alter_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_in',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_out',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
