# Generated by Django 5.2.3 on 2025-10-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_bookings_guestcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='roomID',
            field=models.ForeignKey(db_column='roomID', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
    ]
