# Generated by Django 5.2.3 on 2025-10-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_guests_stays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='guestID',
            field=models.ForeignKey(db_column='guestID', on_delete=django.db.models.deletion.CASCADE, to='backend.guests'),
        ),
        migrations.AlterField(
            model_name='stays',
            name='roomID',
            field=models.ForeignKey(db_column='roomID', on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guestID', models.ForeignKey(db_column='guestID', on_delete=django.db.models.deletion.CASCADE, to='backend.guests')),
                ('roomID', models.ForeignKey(db_column='roomID', on_delete=django.db.models.deletion.CASCADE, to='backend.rooms')),
            ],
        ),
    ]
