# Generated by Django 5.2.3 on 2025-10-15 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_bookings_check_in_alter_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_in',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_out',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
