# Generated by Django 5.2.3 on 2025-10-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_bookings_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='roomID',
            field=models.ForeignKey(db_column='roomID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
    ]
