# Generated by Django 5.2.3 on 2025-10-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_stays_guestid_alter_stays_roomid_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('menuID', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('cookingTime', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('menuItems', models.JSONField(default=list)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Transportation', 'T'), ('Laundary', 'L'), ('Maintainance', 'M'), ('Special Requests', 'Special'), ('HouseKeeping', 'H')], max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'P'), ('Accepted', 'A'), ('Reject', 'R')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(db_column='staffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.staffs')),
                ('stayID', models.ForeignKey(db_column='stayID', on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
        migrations.CreateModel(
            name='Transctions',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('Cash', 'C'), ('Credit Card', 'Credit'), ('Online Payment', 'Online')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(db_column='staffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.staffs')),
                ('stayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stays')),
            ],
        ),
    ]
