# Generated by Django 5.2.3 on 2025-10-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_bookings_check_in_alter_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='check_in',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stays',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
