# Generated by Django 5.2.3 on 2025-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_menus_orders_services_transctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='type',
            field=models.CharField(choices=[('P', 'premium'), ('S', 'Standard'), ('D', 'Deluxe'), ('V', 'VIP')], max_length=100),
        ),
    ]
