# Generated by Django 5.2.3 on 2025-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
