# Generated by Django 5.2.3 on 2025-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_services_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='status',
            field=models.CharField(default='free', max_length=255),
        ),
    ]
